sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # C++14
  - sudo add-apt-repository -y ppa:marutter/rrutter # R
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # R
  - sudo apt-get install -qq r-base r-base-dev
  # R devtools
  - sudo apt-get install libssh2-1-dev
  # pdflatex, used by knitr
  - sudo apt-get install -qq lyx texlive  
  # Rcpp
  - sudo Rscript install_r_packages.R

script: 
  # C++
  - qmake
  - make 
  - ./domagic # Should show nothing and return with zero
  # R wants all non-R files gone...
  - ./clean.sh
  - rm .gitignore
  - rm src/.gitignore
  - rm .travis.yml
  - rm -rf .git
  - rm -rf ..Rcheck
  # Now R is ready to go
  - R CMD check .

after_success:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp14_rcpp/..Rcheck/00check.log

after_failure:
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp14_rcpp/..Rcheck/00check.log
  - cat /home/travis/build/richelbilderbeek/travis_qmake_gcc_cpp14_rcpp/..Rcheck/00install.out
